-- MySQL Script generated by MySQL Workbench
-- Tue Jun 15 17:02:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdcoldigojpa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdcoldigojpa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdcoldigojpa` DEFAULT CHARACTER SET utf8 ;
USE `bdcoldigojpa` ;

-- -----------------------------------------------------
-- Table `bdcoldigojpa`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoldigojpa`.`marca` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcoldigojpa`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoldigojpa`.`produto` (
  `id` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `categoria` TINYINT(1) UNSIGNED NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `capacidade` INT(4) UNSIGNED NOT NULL,
  `valor` DECIMAL(7,2) UNSIGNED NOT NULL,
  `marca_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produto_marca1_idx` (`marca_id` ASC) VISIBLE,
  CONSTRAINT `fk_produto_marca1`
    FOREIGN KEY (`marca_id`)
    REFERENCES `bdcoldigojpa`.`marca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcoldigojpa`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoldigojpa`.`compra` (
  `id` INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `fornecedor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcoldigojpa`.`produtocomprado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoldigojpa`.`produtocomprado` (
  `produto_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `compra_id` INT UNSIGNED ZEROFILL NOT NULL,
  `valor` DECIMAL(7,2) NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`produto_id`, `compra_id`),
  INDEX `fk_produto_has_compra_compra1_idx` (`compra_id` ASC) VISIBLE,
  INDEX `fk_produto_has_compra_produto1_idx` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_produto_has_compra_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `bdcoldigojpa`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_compra_compra1`
    FOREIGN KEY (`compra_id`)
    REFERENCES `bdcoldigojpa`.`compra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
