-- MySQL Script generated by MySQL Workbench
-- Wed Jul 10 20:40:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdcoldigo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdcoldigo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdcoldigo` DEFAULT CHARACTER SET utf8 ;
USE `bdcoldigo` ;

-- -----------------------------------------------------
-- Table `bdcoldigo`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoldigo`.`marcas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdcoldigo`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcoldigo`.`produtos` (
  `id` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `categoria` TINYINT(1) UNSIGNED NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `capacidade` INT(4) UNSIGNED NOT NULL,
  `valor` DECIMAL(7,2) UNSIGNED NOT NULL,
  `marcas_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtos_marcas_idx` (`marcas_id` ASC),
  CONSTRAINT `fk_produtos_marcas`
    FOREIGN KEY (`marcas_id`)
    REFERENCES `bdcoldigo`.`marcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into marcas (nome) values ('Eletrolux'), ('Consul'), ('Prosdócimo');